"""initial schema

Revision ID: e132b17395d6
Revises: 
Create Date: 2026-07-23 22:23:29.845325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e132b17395d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='scan_status'), nullable=False),
    sa.Column('tool_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=True),
    sa.Column('cwe_id', sa.String(length=20), nullable=True),
    sa.Column('owasp_category', sa.String(length=100), nullable=True),
    sa.Column('tool_source', sa.Enum('NESSUS', 'SONARQUBE', 'ZAP', name='tool_source'), nullable=False),
    sa.Column('tool_finding_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_v3', sa.Float(), nullable=True),
    sa.Column('cvss_v4', sa.Float(), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('severity_normalized', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity'), nullable=False),
    sa.Column('location_type', sa.Enum('CODE', 'HOST', 'SERVICE', 'WEB_ENDPOINT', 'CONFIG', name='location_type'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('code_file', sa.String(length=1000), nullable=True),
    sa.Column('code_line', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('parameter', sa.String(length=255), nullable=True),
    sa.Column('proof_of_concept', sa.Text(), nullable=True),
    sa.Column('detection_method', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('false_positive_risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='false_positive_risk'), nullable=True),
    sa.Column('recommended_fix', sa.Text(), nullable=True),
    sa.Column('effort_level', sa.String(length=20), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=True),
    sa.Column('dedup_confidence', sa.Float(), nullable=True),
    sa.Column('remediation_status', sa.Enum('OPEN', 'IN_PROGRESS', 'REMEDIATED', 'RISK_ACCEPTED', 'FALSE_POSITIVE', 'WONT_FIX', name='remediation_status'), nullable=False),
    sa.Column('business_context', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR confidence BETWEEN 0 AND 1', name='ck_findings_confidence_range'),
    sa.CheckConstraint('cvss_v3 IS NULL OR cvss_v3 BETWEEN 0 AND 10', name='ck_findings_cvss_v3_range'),
    sa.CheckConstraint('cvss_v4 IS NULL OR cvss_v4 BETWEEN 0 AND 10', name='ck_findings_cvss_v4_range'),
    sa.CheckConstraint('dedup_confidence IS NULL OR dedup_confidence BETWEEN 0 AND 1', name='ck_findings_dedup_confidence_range'),
    sa.CheckConstraint('epss_score IS NULL OR epss_score BETWEEN 0 AND 1', name='ck_findings_epss_score_range'),
    sa.ForeignKeyConstraint(['canonical_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_cve_id', 'findings', ['cve_id'], unique=False)
    op.create_index('ix_findings_host', 'findings', ['host'], unique=False)
    op.create_index('ix_findings_scan_id', 'findings', ['scan_id'], unique=False)
    op.create_index('ix_findings_severity_normalized', 'findings', ['severity_normalized'], unique=False)
    op.create_index('ix_findings_tool_source', 'findings', ['tool_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_tool_source', table_name='findings')
    op.drop_index('ix_findings_severity_normalized', table_name='findings')
    op.drop_index('ix_findings_scan_id', table_name='findings')
    op.drop_index('ix_findings_host', table_name='findings')
    op.drop_index('ix_findings_cve_id', table_name='findings')
    op.drop_table('findings')
    op.drop_table('scans')
    # ### end Alembic commands ###
